module.exports = `
# Generated by Q2K Keymap parser by 2Cas (c) 2018
# https://github.com/2Cas/Q2K
# This file is released into the public domain as per the CC0 Public Domain
# Dedication (http://creativecommons.org/publicdomain/zero/1.0/)
---

report_mode : auto_nkro # options: auto_nkro, 6kro, nkro

devices:
  %kb_name%:
    id: 0
    layout: default
    layout_offset: 0
    scan_mode:
      mode: %diode_direction% # options:  col_row, row_col, pins, none
      rows: [%row_pins%]
      cols: [%col_pins%]
      # Maps how keys are physically wired, to how they appear visually
      matrix_map: [
%matrix%
      ]
      # Debounce settings
      debounce:
         debounce_time_press: 5
         debounce_time_release: 5
         trigger_time_press: 1
         trigger_time_release: 1
         parasitic_discharge_delay_idle: 10.0
         parasitic_discharge_delay_debouncing: 10.0

layouts:
  default:
    default_layer: 0
    layers: [
%layout%]
    ]

`.trim()